[package]
name = "ant_sim"
version = "1.0.0"
edition = "2021"

[workspace]
members = ["frontend_pixels_winit", "ant_sim_save", "recorder"]

[[bench]]
name="ant_bench"
harness=false

[dependencies]
fasthash = "0.4.0"

[dev-dependencies]
criterion = "0.4"