[package]
name = "frontend_pixels_winit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ant_sim = { path = ".." }
pixels = "0.9"
winit = "0.27"